sudo: false

language: node_js

node_js: 8

notifications:
  email:
    recipients: pyyzcwg2833@outlook.com
    on_success: never
    on_failure: always

env:
  global:
    - GH_REF: github.com/ms-design/ms-design.github.io

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  - yarn run clean
  - yarn run test
  - yarn run build

after_success:
  - bash ./scripts/travis/after-success.sh
